<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\Supplier\" />
    <Folder Include="Dtos\PaymentMethod\" />
    <Folder Include="Interfaces\Repositories\PaymentMethod\" />
    <Folder Include="Interfaces\Repositories\Supplier\" />
    <Folder Include="Interfaces\Services\PaymentMethod\" />
    <Folder Include="Interfaces\Services\Supplier\" />
  </ItemGroup>

</Project>
