// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiTaller.Domain.Models;

public partial class tallerContext : DbContext
{
    public tallerContext(DbContextOptions<tallerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Accione> Acciones { get; set; }

    public virtual DbSet<HistorialInventario> HistorialInventarios { get; set; }

    public virtual DbSet<Inventory> Inventarios { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

    public virtual DbSet<AplicationModule> Modulos { get; set; }

    public virtual DbSet<Operacione> Operaciones { get; set; }

    public virtual DbSet<Product> Productos { get; set; }

    public virtual DbSet<UserRole> Rols { get; set; }

    public virtual DbSet<UserRoleModules> RolModulos { get; set; }

    public virtual DbSet<IdentificationType> TipoIdentificacions { get; set; }

    public virtual DbSet<ProductType> TipoProductos { get; set; }

    public virtual DbSet<User> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

      

      

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PRIMARY");

            entity.ToTable("usuario");

            entity.HasIndex(e => e.IdRol, "FK_USUARIO_ROL");

            entity.HasIndex(e => e.IdTipoIdentificacion, "FK_USUARIO_TIPO_IDENTIFICACION");

            entity.Property(e => e.IdUsuario)
                .HasColumnType("int(11)")
                .HasColumnName("ID_USUARIO");
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CORREO");
            entity.Property(e => e.Estado)
                .HasColumnType("bit(1)")
                .HasColumnName("ESTADO");
            entity.Property(e => e.FechaAsignacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_ASIGNACION");
            entity.Property(e => e.FechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_CREACION");
            entity.Property(e => e.FechaExpiracion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_EXPIRACION");
            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");
            entity.Property(e => e.IdRol)
                .HasColumnType("int(11)")
                .HasColumnName("ID_ROL");
            entity.Property(e => e.IdTipoIdentificacion)
                .HasColumnType("int(11)")
                .HasColumnName("ID_TIPO_IDENTIFICACION");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("NOMBRE_COMPLETO");
            entity.Property(e => e.NumeroIdentificacion)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("NUMERO_IDENTIFICACION");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("PASSWORD");
            entity.Property(e => e.PrimerApellido)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("PRIMER_APELLIDO");
            entity.Property(e => e.PrimerNombre)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("PRIMER_NOMBRE");
            entity.Property(e => e.SegundoApellido)
                .HasMaxLength(255)
                .HasColumnName("SEGUNDO_APELLIDO");
            entity.Property(e => e.SegundoNombre)
                .HasMaxLength(255)
                .HasColumnName("SEGUNDO_NOMBRE");
            entity.Property(e => e.Token)
                .HasMaxLength(255)
                .HasColumnName("TOKEN");
            entity.Property(e => e.Usuario1)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("USUARIO");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USUARIO_ROL");

            entity.HasOne(d => d.IdTipoIdentificacionNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdTipoIdentificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USUARIO_TIPO_IDENTIFICACION");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
