// <auto-generated />
using System;
using ApiTaller.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTaller.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260508144127_Version2")]
    partial class Version2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiTaller.Domain.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("OperationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("operation_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ModuleId" }, "FK_ACTION_APLICATIONMODULE");

                    b.HasIndex(new[] { "OperationId" }, "FK_ACTION_OPERATION");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ACTION_USER");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_BRAND_USER");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.BrandModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BrandId" }, "FK_BRANDMODELVERSION_BRAND");

                    b.HasIndex(new[] { "ModelId" }, "FK_BRANDMODELVERSION_MODELS");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_BRANDMODELVERSION_USER");

                    b.ToTable("BrandModelVersion", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.BrandModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Models")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("models");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_BRANDMODELS_USER");

                    b.ToTable("BrandModels", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identification_number");

                    b.Property<int>("IdentificationTypeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("identification_type_id");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdentificationTypeId" }, "FK_CUSTOMER_IDENTIFICATION_TYPE");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_CUSTOMER_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "UserId" }, "FK_CUSTOMER_USER");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.IdentificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("identification");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsabilidad_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_TYPE_IDENTIFICATION_USER");

                    b.ToTable("identification_type", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int(11)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int(11)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("SupplierId");

                    b.ToTable("inventory_history", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryReception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceImageBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("SupplierId");

                    b.ToTable("inventory_reception", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryReceptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int(11)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceptionId");

                    b.ToTable("inventory_reception_detail", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex(new[] { "UserId" }, "FK_LOGIN_USER");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_MODULE_USER");

                    b.ToTable("module", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_OPERATION_USER");

                    b.ToTable("operation", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_PAYMENT_METHOD_USER");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("Price")
                        .HasColumnType("int(11)")
                        .HasColumnName("price");

                    b.Property<int>("ProducTypeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("product_type_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reference");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("SalePrice")
                        .HasColumnType("int(11)")
                        .HasColumnName("sale_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProducTypeId" }, "FK_PRODUCT_TYPE_PRODUCT");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_PRODUCT_USER");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_TYPE_PRODUCT_USER");

                    b.ToTable("product_type", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.RoleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("action_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActionId" }, "FK_ROLEACTION_ACTION");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ROLEACTION_USER");

                    b.HasIndex(new[] { "RoleId" }, "FK_ROLEACTION_USERROLE");

                    b.ToTable("roleaction", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServiceCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("service_catalog", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServicePriceByVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandModelVersionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("brand_model_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("ServiceCatalogId")
                        .HasColumnType("int")
                        .HasColumnName("service_catalog_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrandModelVersionId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("ServiceCatalogId");

                    b.ToTable("service_price_by_version", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("service_type", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("business_name");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_SUPPLIER_USER");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_surname");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("identification_number");

                    b.Property<int>("IdentificationTypeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("identification_type_id");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("second_last_name");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdentificationTypeId" }, "FK_USER_TYPE_IDENTIFICATION");

                    b.HasIndex(new[] { "UserRoleId" }, "FK_USER_USER_ROLE");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ROLE_USER");

                    b.ToTable("userrole", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRoleModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModulesRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("module_role_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_role_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ModulesRoleId" }, "FK_ROLE_MODULE_MODULE");

                    b.HasIndex(new[] { "UserRoleId" }, "FK_ROLE_MODULE_USER_ROLE");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_USER_ROLE_MODULE_USER");

                    b.ToTable("user_role_module", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int(11)")
                        .HasColumnName("brand_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("customer_id");

                    b.Property<string>("CylinderCapacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cylinder_capacity");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BrandId" }, "FK_VEHICLE_BRAND");

                    b.HasIndex(new[] { "CustomerId" }, "FK_VEHICLE_CUSTOMER");

                    b.HasIndex(new[] { "ModelId" }, "FK_VEHICLE_MODEL");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_VEHICLE_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "VersionId" }, "FK_VEHICLE_VERSION");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("entry_date");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<string>("FuelLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fuel_level");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("Mileage")
                        .HasColumnType("int(11)")
                        .HasColumnName("mileage");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerId" }, "FK_WORK_ORDER_CUSTOMER");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_WORK_ORDER_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "VehicleId" }, "FK_WORK_ORDER_VEHICLE");

                    b.ToTable("work_order", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("evidence_type");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo_url");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_EVIDENCE_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "WorkOrderId" }, "FK_EVIDENCE_WORK_ORDER");

                    b.ToTable("work_order_evidence", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observations");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("ResponsibleUserIdNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ResponsibleUserIdNavigationId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_history", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<ulong>("IsProvidedByCustomer")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_provided_by_customer");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("part_name");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantity");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("warranty_end_date");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "FK_PART_PRODUCT");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_PART_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "WorkOrderId" }, "FK_PART_WORK_ORDER");

                    b.ToTable("work_order_part", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int(11)")
                        .HasColumnName("mechanic_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("warranty_end_date");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MechanicId" }, "FK_SERVICE_MECHANIC");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_SERVICE_RESPONSIBLE_USER");

                    b.HasIndex(new[] { "WorkOrderId" }, "FK_SERVICE_WORK_ORDER");

                    b.ToTable("work_order_service", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Action", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Module", "ModuleIdNavigation")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_ACTION_APLICATIONMODULE");

                    b.HasOne("ApiTaller.Domain.Models.Operation", "OperationIdNavigation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("FK_ACTION_OPERATION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ACTION_USER");

                    b.Navigation("ModuleIdNavigation");

                    b.Navigation("OperationIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Brand", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_BRAND_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.BrandModelVersion", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_BRAND_BRANDMODELVERSION");

                    b.HasOne("ApiTaller.Domain.Models.BrandModels", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK_MODELS_BRANDMODELVERSION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_BRANDMODELVERSION_USER");

                    b.Navigation("Brand");

                    b.Navigation("Model");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.BrandModels", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_BRANDMODELS_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Customer", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.IdentificationType", "IdentificationTypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdentificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_IDENTIFICATION_TYPE");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_CUSTOMER_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.User", "UserIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_USER");

                    b.Navigation("IdentificationTypeNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.IdentificationType", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_TYPE_IDENTIFICATION_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Inventory", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Product", "ProductNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_inventory_product");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_inventory_responsible_user");

                    b.Navigation("ProductNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryHistory", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Product", "ProductNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_inventory_history_product");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_inventory_history_responsible_user");

                    b.HasOne("ApiTaller.Domain.Models.Supplier", "SupplierNavigation")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_inventory_history_supplier");

                    b.Navigation("ProductNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("SupplierNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryReception", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_inventory_reception_responsible_user");

                    b.HasOne("ApiTaller.Domain.Models.Supplier", "SupplierNavigation")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_inventory_reception_supplier");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("SupplierNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryReceptionDetail", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Product", "ProductNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_reception_detail_product");

                    b.HasOne("ApiTaller.Domain.Models.InventoryReception", "ReceptionNavigation")
                        .WithMany("Details")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_reception_detail_reception");

                    b.Navigation("ProductNavigation");

                    b.Navigation("ReceptionNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Login", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_LOGIN_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Module", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_MODULE_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Operation", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_OPERACIONES_USUARIO");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.PaymentMethod", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_PAYMENT_METHOD_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Product", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.ProductType", "ProductTypeIdNavigation")
                        .WithMany()
                        .HasForeignKey("ProducTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT_TYPE_PRODUCT");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_PRODUCT_USER");

                    b.Navigation("ProductTypeIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ProductType", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_TYPE_PRODUCT_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.RoleAction", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Action", "ActionIdNavigation")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLEACTION_ACTION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ROLEACTION_USER");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "RoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLEACTION_USERROLE");

                    b.Navigation("ActionIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("RoleIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServiceCatalog", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_SERVICE_CATALOG_USER");

                    b.HasOne("ApiTaller.Domain.Models.ServiceType", "ServiceTypeIdNavigation")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SERVICE_CATALOG_SERVICE_TYPE");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("ServiceTypeIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServicePriceByVersion", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.BrandModelVersion", "BrandModelVersionIdNavigation")
                        .WithMany()
                        .HasForeignKey("BrandModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SERVICE_PRICE_BRAND_MODEL_VERSION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_SERVICE_PRICE_USER");

                    b.HasOne("ApiTaller.Domain.Models.ServiceCatalog", "ServiceCatalogIdNavigation")
                        .WithMany()
                        .HasForeignKey("ServiceCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SERVICE_PRICE_CATALOG");

                    b.Navigation("BrandModelVersionIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("ServiceCatalogIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ServiceType", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_SERVICE_TYPE_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Supplier", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_SUPPLIER_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.User", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.IdentificationType", "IdentificationTypeIdNavigation")
                        .WithMany()
                        .HasForeignKey("IdentificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_TYPE_IDENTIFICATION");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "UserRoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_USER_ROLE");

                    b.Navigation("IdentificationTypeIdNavigation");

                    b.Navigation("UserRoleIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRole", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ROLE_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRoleModule", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Module", "ModuleIdNavigation")
                        .WithMany()
                        .HasForeignKey("ModulesRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_MODULE_MODULE");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_USER_ROLE_MODULE_USER");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "UserRoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_MODULE_USER_ROLE");

                    b.Navigation("ModuleIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("UserRoleIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Brand", "BrandNavigation")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_BRAND");

                    b.HasOne("ApiTaller.Domain.Models.Customer", "CustomerNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_CUSTOMER");

                    b.HasOne("ApiTaller.Domain.Models.BrandModels", "ModelNavigation")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_MODEL");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_VEHICLE_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.BrandModelVersion", "VersionNavigation")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .HasConstraintName("FK_VEHICLE_VERSION");

                    b.Navigation("BrandNavigation");

                    b.Navigation("CustomerNavigation");

                    b.Navigation("ModelNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("VersionNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrder", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Customer", "CustomerNavigation")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_WORK_ORDER_CUSTOMER");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_WORK_ORDER_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.Vehicle", "VehicleNavigation")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_WORK_ORDER_VEHICLE");

                    b.Navigation("CustomerNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("VehicleNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderEvidence", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_EVIDENCE_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.WorkOrder", "WorkOrderNavigation")
                        .WithMany("Evidences")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EVIDENCE_WORK_ORDER");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("WorkOrderNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderHistory", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserIdNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTaller.Domain.Models.WorkOrder", "WorkOrderNavigation")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_work_order_history_order");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("WorkOrderNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderPart", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Product", "ProductNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_PART_PRODUCT");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_PART_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.WorkOrder", "WorkOrderNavigation")
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PART_WORK_ORDER");

                    b.Navigation("ProductNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("WorkOrderNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrderService", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "MechanicNavigation")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .IsRequired()
                        .HasConstraintName("FK_SERVICE_MECHANIC");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_SERVICE_RESPONSIBLE_USER");

                    b.HasOne("ApiTaller.Domain.Models.WorkOrder", "WorkOrderNavigation")
                        .WithMany("Services")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SERVICE_WORK_ORDER");

                    b.Navigation("MechanicNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("WorkOrderNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryReception", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.WorkOrder", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Parts");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
