// <auto-generated />
using System;
using ApiTaller.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTaller.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260424201634_Version14")]
    partial class Version14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiTaller.Domain.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("OperationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("operation_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ModuleId" }, "FK_ACTION_APLICATIONMODULE");

                    b.HasIndex(new[] { "OperationId" }, "FK_ACTION_OPERATION");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ACTION_USER");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.IdentificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("identification");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsabilidad_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_TYPE_IDENTIFICATION_USER");

                    b.ToTable("identification_type", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int(11)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("product_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "FK_INVENTORY_PRODUCT");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_INVENTORY_USER");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int(11)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int(11)")
                        .HasColumnName("inventory_id");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InventoryId" }, "FK_HISTORY_INVENTORY_INVENTORY");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_HISTORY_INVENTORY_USER");

                    b.ToTable("history_inventory", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex(new[] { "UserId" }, "FK_LOGIN_USER");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_MODULE_USER");

                    b.ToTable("module", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_OPERATION_USER");

                    b.ToTable("operation", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("Price")
                        .HasColumnType("int(11)")
                        .HasColumnName("price");

                    b.Property<int>("ProducTypeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("product_type_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reference");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProducTypeId" }, "FK_PRODUCT_TYPE_PRODUCT");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_PRODUCT_USER");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_TYPE_PRODUCT_USER");

                    b.ToTable("product_type", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.RoleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("action_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActionId" }, "FK_ROLEACTION_ACTION");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ROLEACTION_USER");

                    b.HasIndex(new[] { "RoleId" }, "FK_ROLEACTION_USERROLE");

                    b.ToTable("roleaction", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_surname");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("identification_number");

                    b.Property<int>("IdentificationTypeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("identification_type_id");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("second_last_name");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdentificationTypeId" }, "FK_USER_TYPE_IDENTIFICATION");

                    b.HasIndex(new[] { "UserRoleId" }, "FK_USER_USER_ROLE");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_ROLE_USER");

                    b.ToTable("userrole", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRoleModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("ModulesRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("module_role_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_role_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ModulesRoleId" }, "FK_ROLE_MODULE_MODULE");

                    b.HasIndex(new[] { "UserRoleId" }, "FK_ROLE_MODULE_USER_ROLE");

                    b.HasIndex(new[] { "ResponsibleUserId" }, "FK_USER_ROLE_MODULE_USER");

                    b.ToTable("user_role_module", (string)null);
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Action", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Module", "ModuleIdNavigation")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_ACTION_APLICATIONMODULE");

                    b.HasOne("ApiTaller.Domain.Models.Operation", "OperationIdNavigation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("FK_ACTION_OPERATION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ACTION_USER");

                    b.Navigation("ModuleIdNavigation");

                    b.Navigation("OperationIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.IdentificationType", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_TYPE_IDENTIFICATION_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Inventory", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Product", "ProductIdNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_INVENTORY_PRODUCT");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_INVENTORY_USER");

                    b.Navigation("ProductIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.InventoryHistory", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Inventory", "InventoryIdNavigation")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_HISTORY_INVENTORY_INVENTORY");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_HISTORY_INVENTORY_USER");

                    b.Navigation("InventoryIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Login", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_LOGIN_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Module", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_MODULE_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Operation", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_OPERACIONES_USUARIO");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.Product", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.ProductType", "ProductTypeIdNavigation")
                        .WithMany()
                        .HasForeignKey("ProducTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT_TYPE_PRODUCT");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_PRODUCT_USER");

                    b.Navigation("ProductTypeIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.ProductType", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_TYPE_PRODUCT_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.RoleAction", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Action", "ActionIdNavigation")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLEACTION_ACTION");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ROLEACTION_USER");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "RoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLEACTION_USERROLE");

                    b.Navigation("ActionIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("RoleIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.User", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.IdentificationType", "IdentificationTypeIdNavigation")
                        .WithMany()
                        .HasForeignKey("IdentificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_TYPE_IDENTIFICATION");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "UserRoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_USER_ROLE");

                    b.Navigation("IdentificationTypeIdNavigation");

                    b.Navigation("UserRoleIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRole", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_ROLE_USER");

                    b.Navigation("ResponsibleUserIdNavigation");
                });

            modelBuilder.Entity("ApiTaller.Domain.Models.UserRoleModule", b =>
                {
                    b.HasOne("ApiTaller.Domain.Models.Module", "ModuleIdNavigation")
                        .WithMany()
                        .HasForeignKey("ModulesRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_MODULE_MODULE");

                    b.HasOne("ApiTaller.Domain.Models.User", "ResponsibleUserIdNavigation")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_USER_ROLE_MODULE_USER");

                    b.HasOne("ApiTaller.Domain.Models.UserRole", "UserRoleIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_MODULE_USER_ROLE");

                    b.Navigation("ModuleIdNavigation");

                    b.Navigation("ResponsibleUserIdNavigation");

                    b.Navigation("UserRoleIdNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
