using ApiTaller.Core.Services.Actions;
using ApiTaller.Core.Services.Auth;
using ApiTaller.Core.Services.BrandModels;
using ApiTaller.Core.Services.BrandModelVersions;
using ApiTaller.Core.Services.Brands;
using ApiTaller.Core.Services.Customers;
using ApiTaller.Core.Services.IdentificationTypes;
using ApiTaller.Core.Services.Inventory;
using ApiTaller.Core.Services.Modules;
using ApiTaller.Core.Services.Operations;
using ApiTaller.Core.Services.PaymentMethods;
using ApiTaller.Core.Services.Products;
using ApiTaller.Core.Services.ProductTypes;
using ApiTaller.Core.Services.RoleActions;
using ApiTaller.Core.Services.ServiceCatalogs;
using ApiTaller.Core.Services.ServicePrices;
using ApiTaller.Core.Services.ServiceTypes;
using ApiTaller.Core.Services.Suppliers;
using ApiTaller.Core.Services.UserRoleModules;
using ApiTaller.Core.Services.UserRoles;
using ApiTaller.Core.Services.Users;
using ApiTaller.Core.Services.Vehicles;
using ApiTaller.Core.Services.WorkOrders;
using ApiTaller.Core.Services.Billing;
using ApiTaller.Domain.Interfaces.Services.Actions;
using ApiTaller.Domain.Interfaces.Services.Auth;
using ApiTaller.Domain.Interfaces.Services.BrandModels;
using ApiTaller.Domain.Interfaces.Services.BrandModelVersion;
using ApiTaller.Domain.Interfaces.Services.Brands;
using ApiTaller.Domain.Interfaces.Services.Customers;
using ApiTaller.Domain.Interfaces.Services.IdentificationTypes;
using ApiTaller.Domain.Interfaces.Services.Inventory;
using ApiTaller.Domain.Interfaces.Services.Login;
using ApiTaller.Domain.Interfaces.Services.Module;
using ApiTaller.Domain.Interfaces.Services.Operations;
using ApiTaller.Domain.Interfaces.Services.PaymentMethods;
using ApiTaller.Domain.Interfaces.Services.Products;
using ApiTaller.Domain.Interfaces.Services.ProductTypes;
using ApiTaller.Domain.Interfaces.Services.RoleActions;
using ApiTaller.Domain.Interfaces.Services.ServiceCatalogs;
using ApiTaller.Domain.Interfaces.Services.ServicePrices;
using ApiTaller.Domain.Interfaces.Services.ServiceTypes;
using ApiTaller.Domain.Interfaces.Services.Suppliers;
using ApiTaller.Domain.Interfaces.Services.UserRoleModules;
using ApiTaller.Domain.Interfaces.Services.UserRoles;
using ApiTaller.Domain.Interfaces.Services.Users;
using ApiTaller.Domain.Interfaces.Services.Vehicles;
using ApiTaller.Domain.Interfaces.Services.WorkOrders;
using ApiTaller.Domain.Interfaces.Services.Billing;
using ApiTaller.Domain.Interfaces.Services.WorkshopSettings;
using ApiTaller.Core.Services.WorkshopSettings;
using ApiTaller.Domain.Interfaces.Services.CustomerPortal;
using ApiTaller.Core.Services.CustomerPortal;
using ApiTaller.Domain.Interfaces.Services.Portal;
using ApiTaller.Core.Services.Portal;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace ApiTaller.Core.Services.ServiceConfigurations
{
    public static class Services
    {
        public static IServiceCollection AddServices(this IServiceCollection services)
        {
            services.TryAddScoped<ILoginService, Login.LoginService>();
            services.TryAddScoped<IUserService, UserService>();
            services.TryAddScoped<IAuthService, AuthService>();
            services.TryAddScoped<IUserRoleService, UserRoleService>();
            services.TryAddScoped<IModuleService, ModuleService>();
            services.TryAddScoped<IActionService, ActionService>();
            services.TryAddScoped<IUserRoleModuleService, UserRoleModuleService>();
            services.TryAddScoped<IOperationService, OperationService>();
            services.TryAddScoped<IRoleActionService, RoleActionService>();
            services.TryAddScoped<IIdentificationTypesService, IdentificationTypesService>();
            services.TryAddScoped<IProductService, ProductService>();
            services.TryAddScoped<IProductTypeService, ProductTypeService>();
            services.TryAddScoped<IBrandService, BrandService>();
            services.TryAddScoped<IBrandModelsService, BrandModelService>();
            services.TryAddScoped<IBrandModelVersionService, BrandModelVersionService>();
            services.TryAddScoped<IPaymentMethodService, PaymentMethodService>();
            services.TryAddScoped<ISupplierService, SupplierService>();
            services.TryAddScoped<ICustomerService, CustomerService>();
            services.TryAddScoped<IVehicleService, VehicleService>();
            services.TryAddScoped<IWorkOrderService, WorkOrderService>();
            services.TryAddScoped<IServiceTypeService, ServiceTypeService>();
            services.TryAddScoped<IServiceCatalogService, ServiceCatalogService>();
            services.TryAddScoped<IInventoryReceptionService, InventoryReceptionService>();
            services.TryAddScoped<IServicePriceByVersionService, ServicePriceByVersionService>();
            services.TryAddScoped<IInventoryService, InventoryService>();
            services.TryAddScoped<IBillingService, BillingService>();
            services.TryAddScoped<IWorkshopSettingsService, WorkshopSettingsService>();
            services.TryAddScoped<ICustomerPortalService, CustomerPortalService>();
            services.TryAddScoped<ApiTaller.Domain.Interfaces.Services.Portal.IPortalService, ApiTaller.Core.Services.Portal.PortalService>();
            services.TryAddScoped<ApiTaller.Domain.Interfaces.Services.Agenda.IAgendaService, ApiTaller.Core.Services.Agenda.AgendaService>();
            services.TryAddScoped<ApiTaller.Domain.Interfaces.Services.Email.IEmailSettingsService, ApiTaller.Core.Services.Email.EmailSettingsService>();
            services.TryAddScoped<ApiTaller.Domain.Interfaces.Services.IDashboardService, ApiTaller.Core.Services.Dashboard.DashboardService>();
            return services;
        }
    }
}
