<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiTaller.Core\ApiTaller.Core.csproj" />
    <ProjectReference Include="..\ApiTaller.Domain\ApiTaller.Domain.csproj" />
    <ProjectReference Include="..\ApiTaller.Infrastructure\ApiTaller.Infrastructure.csproj" />
  </ItemGroup>

</Project>
